version: '3.8'
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3001:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase
      - MB_DB_PASS=metabase_password
      - MB_DB_HOST=host.docker.internal
      - MB_SITE_URL=http://62.109.26.35/metabase
    volumes:
      - metabase-data:/metabase-data
    restart: unless-stopped
    network_mode: host

volumes:
  metabase-data:
